apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
spec:
  replicas: 2  # Number of replicas (adjust as needed)
  selector:
    matchLabels:
      app: javaapp  # Label selector to match pods
  template:
    metadata:
      labels:
        app: javaapp  # Ensure this label matches the service selector
    spec:
      containers:
        - name: javaapp
          image: premgowda07/javaapp_241047037  # Docker image name (replace if necessary)
          ports:
            - containerPort: 8000  # Expose port 8000 inside the container (matches your Dockerfile)
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: javaapp  # Service selector to match the deployment's pods
  ports:
    - protocol: TCP
      port: 80       # Expose port 80 externally
      targetPort: 8000  # Forward traffic to container port 8000
      nodePort: 30000  # NodePort on your Kubernetes node (ensure it's available)
  type: NodePort  # Service type: expose it externally via NodePort
