apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
spec:
  replicas: 2  # Adjust the number of replicas if needed
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: javaapp
          image: premgowda07/javaapp_241047037  # Replace with your Docker image name
          ports:
            - containerPort: 8000  # Expose port 8000 inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: javaapp  # This will select the pods created by the deployment
  ports:
    - protocol: TCP
      port: 80  # Expose port 80 for external access
      targetPort: 8000  # Map it to port 8000 in the container
      nodePort:   # The port on the node (accessible externally)
  type: NodePort  # Expose the service as a NodePort (for local access)
